config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/emails'
  end

  get 'home/index'

  get 'resources/index'
  get 'resources/new'
  post 'resources/create'
  get 'resources/show'
  get 'resources/edit'
  put 'resources/update'
  delete 'resources/destroy'

  get 'categories/index'
  get 'categories/new'
  post 'categories/create'
  get 'categories/show'
  get 'categories/edit'
  put 'categories/update'
  delete 'categories/destroy'

  get 'transactions/index'
  get 'transactions/new'
  post 'transactions/create'
  get 'transactions/show'
  get 'transactions/edit'
  put 'transactions/update'
  delete 'transactions/destroy'

  get 'statistics/index'
  get 'statistics/categories'
  get 'statistics/resources'

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

end

app/views/resources/edit.html.erb
<h1>Edycja zasobu:</h1>
<%= form_for @resource, url: resources_update_path(@resource), method: :put do |f| %>
	<div class="form-group">
		<%= f.label :name, "Nazwa:" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :value, "Wartość:" %>
		<em>[zł]</em>
		<%= f.text_field :value, class: "form-control", :value => (number_with_precision(@resource.value, :precision => 2)).sub!(".", ",") %>
	</div>

	<p><%= f.submit "Aktualizuj zasób", class: "btn btn-primary"%></p>
<% end %>

<p><%= link_to "Powrót do zasobów", resources_index_path, class: "linkto" %></p>

app/views/resources/index.html.erb
<h1>Twoje zasoby</h1>

<div class="addlinkdiv">
	<p><%= link_to "Dodaj nowy zasób", resources_new_path, class: "addlink" %></p>
</div>
<% i=0 %>
<table  class="table table-hover">
  <thead>
  <th>Nr.</th>
  <th>Nazwa</th>
  <th>Wielkość</th>
  <th>Szczegóły</th>
  <th>Edytuj</th>
  <th>Usuń</th>
  </thead>
  <tbody>
	<% @resources.each do |f| %>
		<tr>
			<td><%= i+=1 %></td>
			<td><%= f.name %></td>
			<td><%= number_with_precision(f.value, :precision => 2).sub!(".", ",") %> zł</td>
			<td><%= link_to "Szczegóły", resources_show_path(f), :class => "btn btn-info"%></td>
	        <td><%= link_to "Edytuj", resources_edit_path(f), :class => "btn btn-primary"%></td>
	        <td><%= link_to "Usuń", resources_destroy_path(f), method: :delete, data: { confirm: 'Na pewno usunąć ten zesób?' }, :class => "btn btn-danger"%></td>
		</tr>
	<% end %>
  </tbody>
</table>
<%= will_paginate @resources, renderer: BootstrapPagination::Rails, :previous_label => '<span aria-hidden="true">&laquo;</span>', :next_label => '<span aria-hidden="true">&raquo;</span>' %>

app/views/resources/new.html.erb
<h1>Dodawanie zasobu:</h1>
<%= form_for @resource, url: resources_create_path do |f| %>
	<div class="form-group">
		<%= f.label :name, "Nazwa:" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :value, "Wartość:" %>
		<em>[zł]</em>
		<%= f.text_field :value, class: "form-control" %>
	</div>

	<p><%= f.submit "Dodaj zasób", class: "btn btn-primary"%></p>
<% end %>

<p><%= link_to "Powrót do zasobów", resources_index_path, class: "linkto" %></p>

app/views/resources/show.html.erb
<h1>Zasób: <%= @resource.name %></h1>

<div id="resourceshowdiv">
	<table class="table table-hover">
	    <tr>
	    	<td id="firstrow">Nazwa:</td>
	      	<td id="firstrow"><%= @resource.name %></td>
	    </tr>
	    <tr>
	    	<td>Wartość:</td>
	      	<td><%= (number_with_precision(@resource.value, :precision => 2)).sub!(".", ",") %> zł</td>
	    </tr>
	</table>
</div>

<p><%= link_to "Powrót do zasobów", resources_index_path, class: "linkto" %></p>