config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/emails'
  end

  get 'home/index'

  get 'resources/index'
  get 'resources/new'
  post 'resources/create'
  get 'resources/show'
  get 'resources/edit'
  put 'resources/update'
  delete 'resources/destroy'

  get 'categories/index'
  get 'categories/new'
  post 'categories/create'
  get 'categories/show'
  get 'categories/edit'
  put 'categories/update'
  delete 'categories/destroy'

  get 'transactions/index'
  get 'transactions/new'
  post 'transactions/create'
  get 'transactions/show'
  get 'transactions/edit'
  put 'transactions/update'
  delete 'transactions/destroy'

  get 'statistics/index'
  get 'statistics/categories'
  get 'statistics/resources'

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :transactions

  validates :name, presence: true
  validates :user, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authenticate_user!

  def index
    @categories = current_user.categories.paginate(:page => params[:page], :per_page => 20)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if current_user.categories << @category
      flash[:success] = "Pomyślnie dodano kategorię!"
      redirect_to categories_index_path
    else
      flash[:alert] = "Nieprawidłowe dane!"
      render :new
    end
  end

  def show
    begin
      @category = current_user.categories.find(params[:format])
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie jesteś właścicielem tej kategorii!"
      redirect_to categories_index_path
    end
  end

  def edit
    begin
      @category = current_user.categories.find(params[:format])
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie jesteś właścicielem tej kategorii!"
      redirect_to categories_index_path
    end
  end

  def update
    begin
      @category = current_user.categories.find(params[:format])
      if @category.update(category_params)
        flash[:success] = "Pomyślnie zaktualizowano kategorię!"
        redirect_to categories_index_path
      else
        flash[:alert] = "Nieprawidłowe dane!"
        render :edit
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie jesteś właścicielem tej kategorii!"
      redirect_to categories_index_path
    end
  end

  def destroy
    begin
      @category = current_user.categories.find(params[:format])
      if current_user.categories.size > 1
        @category.destroy
        flash[:success] = "Pomyślnie usunięto kategorię!"
      else
        flash[:alert] = "Nie możesz usunąć jedynej kategorii!"
      end
      redirect_to categories_index_path
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie jesteś właścicielem tej kategorii!"
      redirect_to categories_index_path
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h1>Edycja kategorii:</h1>
<%= form_for @category, url: categories_update_path(@category), method: :put do |f| %>
	<div class="form-group">
		<%= f.label :name, "Nazwa:" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>

	<p><%= f.submit "Aktualizuj kategorię", class: "btn btn-primary"%></p>
<% end %>

<p><%= link_to "Powrót do kategorii", categories_index_path, class: "linkto" %></p>

app/views/categories/index.html.erb
<h1>Twoje kategorie</h1>

<div class="addlinkdiv">
	<p><%= link_to "Dodaj nową kategorię", categories_new_path, class: "addlink" %></p>
</div>

<% i=0 %>
<table  class="table table-hover">
  <thead>
  <th>Nr.</th>
  <th>Nazwa</th>
  <th>Szczegóły</th>
  <th>Edytuj</th>
  <th>Usuń</th>
  </thead>
  <tbody>
	<% @categories.each do |f| %>
		<tr>
			<td><%= i+=1 %></td>
			<td><%= f.name %></td>
			<td><%= link_to "Szczegóły", categories_show_path(f), :class => "btn btn-info"%></td>
	        <td><%= link_to "Edytuj", categories_edit_path(f), :class => "btn btn-primary"%></td>
	        <td><%= link_to "Usuń", categories_destroy_path(f), method: :delete, data: { confirm: 'Na pewno usunąć ten zesób?' }, :class => "btn btn-danger"%></td>
		</tr>
	<% end %>
  </tbody>
</table>
<%= will_paginate @resources, renderer: BootstrapPagination::Rails, :previous_label => '<span aria-hidden="true">&laquo;</span>', :next_label => '<span aria-hidden="true">&raquo;</span>' %>

app/views/categories/new.html.erb
<h1>Dodawanie kategorii:</h1>
<%= form_for @category, url: categories_create_path do |f| %>
	<div class="form-group">
		<%= f.label :name, "Nazwa:" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<p><%= f.submit "Dodaj kategorię", class: "btn btn-primary"%></p>
<% end %>

<p><%= link_to "Powrót do kategorii", categories_index_path, class: "linkto" %></p>

app/views/categories/show.html.erb
<h1>Kategoria: <%= @category.name %></h1>

<div id="categoryshowdiv">
	<table class="table table-hover">
	    <tr>
	    	<td id="firstrow">Nazwa:</td>
	      	<td id="firstrow"><%= @category.name %></td>
	    </tr>
	</table>
</div>

<p><%= link_to "Powrót do kategorii", categories_index_path, class: "linkto" %></p>