config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/emails'
  end

  get 'home/index'

  get 'resources/index'
  get 'resources/new'
  post 'resources/create'
  get 'resources/show'
  get 'resources/edit'
  put 'resources/update'
  delete 'resources/destroy'

  get 'categories/index'
  get 'categories/new'
  post 'categories/create'
  get 'categories/show'
  get 'categories/edit'
  put 'categories/update'
  delete 'categories/destroy'

  get 'transactions/index'
  get 'transactions/new'
  post 'transactions/create'
  get 'transactions/show'
  get 'transactions/edit'
  put 'transactions/update'
  delete 'transactions/destroy'

  get 'statistics/index'
  get 'statistics/categories'
  get 'statistics/resources'

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  def index
      @transactions = current_user.transactions
        .search(params[:search])
        .dateSearch(date_search)
        .categorySearch(category_search)
        .resourceSearch(resource_search)
        .paymentSearch(payment_search)
        .typeSearch(type_search)
        .order((sort_column.empty? ? "id" : sort_column) + ' ' + sort_direction)
        .paginate(:page => params[:page], :per_page => 20)
  end

  def new
    @transaction = Transaction.new
  end

  def create
    begin
      @transaction = Transaction.new(correct_transaction_params)
      if current_user.transactions << @transaction
        resource = correct_transaction_params[:resource]
        if transaction_params[:type] == 1.to_s
          resource.value += correct_transaction_params[:value].to_f
        elsif transaction_params[:type] == 2.to_s
          resource.value -= correct_transaction_params[:value].to_f
        end
        resource.save

        flash[:success] = "Pomyślnie dodano transakcję!"
        redirect_to transactions_index_path
      else
        flash[:alert] = "Nieprawidłowe dane!"
        render :new
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nieprawidłowe dane!"
      render :new
    end
  end

  def show
    begin
      @transaction = current_user.transactions.find(params[:format])
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie jesteś właścicielem tej transakcji!"
      redirect_to transactions_index_path
    end
  end

  def edit
    begin
      @transaction = current_user.transactions.find(params[:format])
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie jesteś właścicielem tej transakcji!"
      redirect_to transactions_index_path
    end
  end

  def update
    begin
      allow_comma(transaction_params[:value])
      @transaction = current_user.transactions.find(params[:format])
      @transaction.name = transaction_params[:name]
      @transaction.value = transaction_params[:value]
      @transaction.shoppingTime = transaction_params[:shoppingTime]
      @transaction.description = transaction_params[:description]
      @transaction.payment = Payment.find(transaction_params[:payment].to_i)
      @transaction.type = Type.find(transaction_params[:type].to_i)
      @transaction.resource = current_user.resources.find(transaction_params[:resource].to_i)
      @transaction.category = current_user.categories.find(transaction_params[:category].to_i)
      if @transaction.save
        flash[:success] = "Pomyślnie zaktualizowano transakcję!"
        redirect_to transactions_index_path
      else
        flash[:alert] = "Nieprawidłowe dane!"
        render :new
      end
      rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nieprawidłowe dane!"
      redirect_to transactions_index_path
    end
  end

  def destroy
    begin
      @transaction = current_user.transactions.find(params[:format])
      @transaction.destroy
      flash[:success] = "Pomyślnie usunięto transakcję!"
      redirect_to transactions_index_path
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Nie jesteś właścicielem tej transakcji!"
      redirect_to transactions_index_path
    end
  end

  private
  def transaction_params
    params.require(:transaction).permit(:name, :value, :shoppingTime, :description, :payment, :type, :resource, :category)
  end

  def allow_comma(number_string)
    number_string.sub(",", ".")
  end

  def correct_transaction_params
    corret = Hash.new(8)
    corret[:name] = transaction_params[:name]
    corret[:value] = allow_comma(transaction_params[:value]) unless transaction_params[:value].nil?
    corret[:shoppingTime] = transaction_params[:shoppingTime]
    corret[:description] = transaction_params[:description]
    corret[:payment] = Payment.find(transaction_params[:payment].to_i)
    corret[:type] = Type.find(transaction_params[:type].to_i)
    corret[:resource] = current_user.resources.find(transaction_params[:resource].to_i)
    corret[:category] = current_user.categories.find(transaction_params[:category].to_i)
    corret
  end

  def sort_column
    Transaction.column_names.include?(params[:sort]) ? params[:sort] : ""
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def date_search
    params[:date].present? ? params[:date].to_i : 0
  end

  def category_search
    params[:category].present? ? params[:category].to_i : 0
  end

  def resource_search
    params[:resource].present? ? params[:resource].to_i : 0
  end

  def payment_search
    params[:payment].present? ? params[:payment].to_i : 0
  end

  def type_search
    params[:type].present? ? params[:type].to_i : 0
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_transactions.html.erb
<% i=0 %>
	<table class="table table-hover">
		<thead>
		<th>
			<%= link_to transactions_index_path(sortable("id")), class: "sortinglink" do %>
				Nr.<%= column_name("id") %>
			<% end %>
		</th>
		<th>
			<%= link_to transactions_index_path(sortable("name")), class: "sortinglink" do %>
				Nazwa<%= column_name("name") %>
			<% end %>
		</th>
		<th>
			<%= link_to transactions_index_path(sortable("value")), class: "sortinglink" do %>
				Wartość<%= column_name("value") %>
			<% end %>
		</th>
		<th>Szczegóły</th>
		<th>Edytuj</th>
	 	<th>Usuń</th>
	  	</thead>
	  	<tbody>
		<% @transactions.each do |f| %>
			<tr>
				<td><%= i+=1 %></td>
				<td><%= f.name %></td>
				<td><%= number_with_precision(f.value, :precision => 2).sub!(".", ",") %> zł</td>
				<td><%= link_to "Szczegóły", transactions_show_path(f), :class => "btn btn-info"%></td>
		        <td><%= link_to "Edytuj", transactions_edit_path(f), :class => "btn btn-primary"%></td>
		        <td><%= link_to "Usuń", transactions_destroy_path(f), method: :delete, data: { confirm: 'Na pewno usunąć ten zesób?' }, :class => "btn btn-danger"%></td>
			</tr>
		<% end %>
	  </tbody>
	</table>

<%= will_paginate @transactions, renderer: BootstrapPagination::Rails, :previous_label => '<span aria-hidden="true">&laquo;</span>', :next_label => '<span aria-hidden="true">&raquo;</span>' %>

app/views/transactions/edit.html.erb
<h1>Edycja transakcji:</h1>
<%= form_for @transaction, url: transactions_update_path(@transaction), method: :put do |f| %>
	<div class="form-group">
		<%= f.label :name, "Nazwa:" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :value, "Wartość:" %>
		<em>[zł]</em>
		<%= f.text_field :value, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :shoppingTime, "Data:" %>
		<div class='input-group date' id='datetimepicker'>
            <%= f.text_field :shoppingTime, class: "form-control", :value => @transaction.shoppingTime.strftime("%d.%m.%Y %H:%M:%S")%>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
	</div>
	<div class="form-group">
		<%= f.label :resource, "Zasób:" %>
		<%= f.select(:resource, current_user.resources.map { |e| [e.name, e.id] }, {:selected => @transaction.resource.id}, {:class => "form-control"}) %>
	</div>
	<div class="form-group">
		<%= f.label :category, "Kategoria:" %>
		<%= f.select(:category, current_user.categories.map { |e| [e.name, e.id] }, {:selected => @transaction.category.id}, {:class => "form-control"}) %>
	</div>
	<div class="form-group">
		<%= f.label :type, "Typ:" %>
		<%= f.select(:type, Type.all.map { |e| [e.name, e.id] }, {:selected => @transaction.type.id}, {:class => "form-control"}) %>
	</div>
	<div class="form-group">
		<%= f.label :payment, "Płatność:" %>
		<%= f.select(:payment, Payment.all.map { |e| [e.name, e.id] }, {:selected => @transaction.payment.id}, {:class => "form-control"}) %>
	</div>
	<div class="form-group">
		<%= f.label :description, "Opis:"%>
		<% if @transaction.description.present? %>
			<em id="descriptionlabel">(Ukryj)</em>
			<%= f.text_area :description, class: "form-control text-area", :rows => 5 %>
		<% else %>
			<em id="descriptionlabel">(Pokaż)</em>
			<%= f.text_area :description, class: "form-control text-area", style: "display: none", :rows => 5 %>
		<% end %>
	</div>

	<p><%= f.submit "Aktualizuj transakcję", class: "btn btn-primary"%></p>
<% end %>

<p><%= link_to "Powrót do transakcji", transactions_index_path, class: "linkto" %></p>

app/views/transactions/index.html.erb
<h1>Twoje kategorie</h1>

<div class="addlinkdiv">
	<p><%= link_to "Dodaj nową transakcję", transactions_new_path, class: "addlink"%></p>
</div>

<div id="serarchdiv">
	<%= form_tag transactions_index_path, :method => :get, :class => "navbar-form navbar-left", :role => "search", :id => "transactions_search", :enforce_utf8 => false do %>
		<table class="table" id="searchtable">
			<thead>
				<th class="col-md-2 col-xs-2 col-sm-2 col-lg-2">Wyszukaj:</th>
				<th class="col-md-2 col-xs-2 col-sm-2 col-lg-2">Data:</th>
				<th class="col-md-2 col-xs-2 col-sm-2 col-lg-2">Kategoria:</th>
				<th class="col-md-2 col-xs-2 col-sm-2 col-lg-2">Zasób:</th>
				<th class="col-md-2 col-xs-2 col-sm-2 col-lg-2">Płatność:</th>
				<th class="col-md-2 col-xs-2 col-sm-2 col-lg-2">Typ:</th>
			</thead>
			<tbody>
				<tr>
			<td>
				<!-- <div class="form-group"> -->
			    	<%= text_field_tag :search, params[:search], placeholder: "Wyszukaj", class: "form-control" %>
			  	<!-- </div> -->
			</td>
			<td>
			  	<!-- <div class="form-group"> -->
				  	<%= select_tag :date, options_for_select([['Wszystkie', 0], ['Dziś', 1], ['Tydzień', 2], ['2 Tygodnie', 3], ['Miesiąc', 4], ['3 Miesiące', 5], ['Pół roku', 6], ['Rok', 7]], params[:date]), id: "datesearch", class: "form-control"%>
			  	<!-- </div> -->
			</td>
			<td>
			  	<!-- <div class="form-group"> -->
				  	<%= select_tag :category, options_for_select([['Wszystkie', 0]]+@current_user.categories.collect{ |u| [u.name, u.id] }, params[:category]), id: "categorysearch", class: "form-control"%>
			  	<!-- </div> -->
			</td>
			<td>
			  	<!-- <div class="form-group"> -->
				  	<%= select_tag :resource, options_for_select([['Wszystkie', 0]]+@current_user.resources.collect{ |u| [u.name, u.id] }, params[:resource]), id: "resourcesearch", class: "form-control"%>
			  	<!-- </div> -->
			</td>
			<td>
			  	<!-- <div class="form-group"> -->
				  	<%= select_tag :payment, options_for_select([['Wszystkie', 0]]+Payment.all.collect{ |u| [u.name, u.id] }, params[:payment]), id: "paymentsearch", class: "form-control"%>
			  	<!-- </div> -->
			</td>
			<td>
			  	<!-- <div class="form-group"> -->
				  	<%= select_tag :type, options_for_select([['Wszystkie', 0]]+Type.all.collect{ |u| [u.name, u.id] }, params[:type]), id: "typesearch", class: "form-control"%>
		  		<!-- </div> -->
			</td>
		   <!-- <%= submit_tag "Wyszukaj", :name => nil, class: "btn btn-default" %> -->
		   			</tr>
			</tbody>
		</table>
	<% end %>
</div>

<div id="transactions">
	<%= render 'transactions' %>
</div>

app/views/transactions/index.js.erb
$('#transactions').html('<%= escape_javascript(render("transactions")) %>');

app/views/transactions/new.html.erb
<h1>Dodawanie transakcji:</h1>
<%= form_for @transaction, url: transactions_create_path do |f| %>
	<div class="form-group">
		<%= f.label :name, "Nazwa:" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :value, "Wartość:" %>
		<em>[zł]</em>
		<%= f.text_field :value, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :shoppingTime, "Data:" %>
		<div class='input-group date' id='datetimepicker'>
            <%= f.text_field :shoppingTime, class: "form-control"%>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
	</div>
	<div class="form-group">
		<%= f.label :resource, "Zasób:" %>
		<%= f.select(:resource, current_user.resources.map { |e| [e.name, e.id] }, {}, {:class => "form-control"}) %>
	</div>
	<div class="form-group">
		<%= f.label :category, "Kategoria:" %>
		<%= f.select(:category, current_user.categories.map { |e| [e.name, e.id] }, {}, {:class => "form-control"}) %>
	</div>
	<div class="form-group">
		<%= f.label :type, "Typ:" %>
		<%= f.select(:type, Type.all.map { |e| [e.name, e.id] }, {}, {:class => "form-control"}) %>
	</div>
	<div class="form-group">
		<%= f.label :payment, "Płatność:" %>
		<%= f.select(:payment, Payment.all.map { |e| [e.name, e.id] }, {}, {:class => "form-control"}) %>
	</div>
	<div class="form-group">
		<%= f.label :description, "Opis:"%>
		<em id="descriptionlabel">(Pokaż)</em>
		<%= f.text_area :description, class: "form-control text-area", style: "display: none", :rows => 5 %>
	</div>

	<p><%= f.submit "Dodaj transakcję", class: "btn btn-primary"%></p>
<% end %>

<p><%= link_to "Powrót do transakcji", transactions_index_path, class: "linkto" %></p>

app/views/transactions/show.html.erb
<h1>Transakcja: <%= @transaction.name %></h1>

<div id="transactionshowdiv">
	<table class="table table-hover">
	    <tr>
	    	<td id="firstrow">Nazwa:</td>
	      	<td id="firstrow"><%= @transaction.name %></td>
	    </tr>
	    <tr>
	    	<td>Wartość:</td>
	      	<td><%= (number_with_precision(@transaction.value, :precision => 2)).sub!(".", ",") %> zł</td>
	    </tr>
	    <tr>
	    	<td>Data:</td>
	      	<td><%= @transaction.shoppingTime.strftime("%d.%m.%Y %k:%M") %></td>
	    </tr>
	    <tr>
	    	<td>Zasób:</td>
	      	<td><%= @transaction.resource.name %></td>
	    </tr>
	    <tr>
	    	<td>Kategria:</td>
	      	<td><%= @transaction.category.name %></td>
	    </tr>
	    <tr>
	    	<td>Typ:</td>
	      	<td><%= @transaction.type.name %></td>
	    </tr>
	    <tr>
	    	<td>Płatność:</td>
	      	<td><%= @transaction.payment.name %></td>
	    </tr>
	    <% if @transaction.description.present? %>
	    	<tr>
		    	<td id="descriptiontd">Opis:</td>
		      	<td><%= simple_format h @transaction.description %></td>
		    </tr>
	    <% end %>
	</table>
</div>

<p><%= link_to "Powrót do transakcji", transactions_index_path, class: "linkto" %></p>