config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/emails'
  end

  get 'home/index'

  get 'resources/index'
  get 'resources/new'
  post 'resources/create'
  get 'resources/show'
  get 'resources/edit'
  put 'resources/update'
  delete 'resources/destroy'

  get 'categories/index'
  get 'categories/new'
  post 'categories/create'
  get 'categories/show'
  get 'categories/edit'
  put 'categories/update'
  delete 'categories/destroy'

  get 'transactions/index'
  get 'transactions/new'
  post 'transactions/create'
  get 'transactions/show'
  get 'transactions/edit'
  put 'transactions/update'
  delete 'transactions/destroy'

  get 'statistics/index'
  get 'statistics/categories'
  get 'statistics/resources'

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twoje finanse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body class="container">

<div id="loginbar">
	<% if current_user %>
		Jesteś zalogowany jako: <b><%= current_user.name %> <%= current_user.surname %></b> (<%= link_to "Wyloguj", destroy_user_session_path, method: :delete  %>)
	<% else %>
		<%= link_to "Zarejestruj", new_user_registration_path %> | <%= link_to "Zaloguj", new_user_session_path  %>
	<% end %>
</div>
<div id="menudiv">
	<ul class="nav nav-pills nav-justified">
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "home" %>" ><%= link_to "Strona domowa", home_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "transactions" %>" ><%= link_to "Transakcje", transactions_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "resources" %>"><%= link_to "Zasoby", resources_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "categories" %>"><%= link_to "Kategorie", categories_index_path %></li>
	  <li role="presentation" class="menuitem <%= "active" if controller.controller_name == "statistics" %>"><%= link_to "Statystyki", statistics_index_path %></li>
	</ul>
</div>

<div id="flashalert">
	<%= render partial: "shared/flash_messages", flash: flash %>
</div>

<%= yield %>

</body>
</html>